### ISSUE TITLE
Why don't we abort transactions?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#118]
Should we be aborting mongodb transactions that don't complete?  We just start it and then drop it if there is an exception - not doing any "using", etc.  Should this change?

**Comment by johnml1135** [comment]
@ddaspit do you have any insight into this?

**Comment by Enkidu93** [comment]
The current implementation ought to be safe. Only one transaction is allowed per session (see [here](https://www.mongodb.com/docs/manual/core/transactions/#transactions-and-sessions)) and transactions only last for one minute (couldn't find this in the docs but see [here](https://www.dbta.com/Columns/MongoDB-Matters/Limitations-in-MongoDB-Transactions-127057.aspx)). I think the only way we could run into problems is if two transactions are started with `BeginTransactionAsync()` in the code base because it doesn't really begin a new transaction. (You could play it extra safe and abort the existing transaction if `IsInTransaction` is true). Of course, if a failure mid-transaction causes an exception to be thrown which ultimately causes the data access context to be disposed (thereby aborting the transaction), it wouldn't be an issue. And since it's a scoped service, I don't think this will be an issue. 

If this is satisfactory, I will close this issue.
