### ISSUE TITLE
If unsupported engine tries to be created, have appropriate error

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#13]

**Comment by johnml1135** [comment]
That is, in the API reply.

**Comment by Enkidu93** [comment]
Just saw this issue as I was scanning the board: I think this works, right? It replies with a 400. Did you want something more to be done?

**Comment by Enkidu93** [comment]
@johnml1135, did you see my above comment? I'm not sure what this means because at the moment we're throwing a 400 when a user attempts to create some non-Nmt, non-SmtTransfer, etc. engine, and it's in the API docs that that's an intended behavior. Are you just saying you'd prefer a different status code thrown?

**Comment by johnml1135** [comment]
This was created to make sure it was resolved.  A 400 code with an intelligent error is fine :-)
