### ISSUE TITLE
E2E - don't have adjacent folders

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#158]
If they are adjacent, machine will find the Serval projects rather than pulling the nugget packages.  This will not catch errors where we don't publish the Serval updates (GRPC, Client and DataAccess).  This change should be made to Serval and Machine E2E Tests.
They can be in any folders, just not adjacent (as they should be in the development environment.)

**Comment by Enkidu93** [comment]
This is getting caught in Machine [here](https://github.com/sillsdev/machine/actions/runs/6501020982). Because of the way the docker compose is set up, separating the two of them won't work without some finagling (see [here](https://github.com/sillsdev/serval/actions/runs/6551318142)). Is it sufficient that they're caught in Machine? Can we leave this as is? @johnml1135

**Comment by johnml1135** [comment]
I believe we should still find a way to resolve this.  I can't tell from the failing builds what exactly is going on.  We can need to discuss.

**Comment by johnml1135** [comment]
We should be able to do some templating (interpolation) of the docker-compose file to make it work:
* https://stackoverflow.com/questions/45899399/template-syntax-in-compose-file-docker
* https://docs.docker.com/compose/compose-file/12-interpolation/
