### ISSUE TITLE
SF: Upload Paratext USFM to Serval

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#173]
See issue 26 here: https://docs.google.com/spreadsheets/d/13Y8d3z3JajAoR2B1zDbsjb0q_GLVQaB6iX9rZPM9it4/edit#gid=0

**Comment by pmachapman** [comment]
**Rationale**
 * Serval USFM, other checking and lower resources all indicate that USFM should be better for Serval to use

**Tasks**
 * SF: Convert the back end to using the Paratext projects and the chapter filtering instead of uploading a file per chapter.

**Notes**
 * Chapter filtering is to be added in #169
 * Support for uploading the USFM was added in sillsdev/web-xforge#2286, and published in version [5.0.3](https://github.com/sillsdev/web-xforge/releases/tag/SFv5.0.3)
 * See [SF-2310](https://jira.sil.org/browse/SF-2310) for details.

**To Do**
 * Book filtering (this was accidentally omitted from in sillsdev/web-xforge#2286)

**Comment by johnml1135** [comment]
@pmachapman - You can filter books in Serval directly - https://github.com/sillsdev/serval/issues/202.  Chapters are coming in the next 2 weeks: https://github.com/sillsdev/serval/issues/150.

**Comment by Nateowami** [comment]
Just to be clear, we're talking about uploading the entire project, not just USFM files, right? So KBTs and everything else will get sent along?

**Comment by Nateowami** [comment]
How does this differ from #169?

**Comment by pmachapman** [comment]
> Just to be clear, we're talking about uploading the entire project, not just USFM files, right? So KBTs and everything else will get sent along?

Yes.

> How does this differ from https://github.com/sillsdev/serval/issues/169?

It is just the first half of that issue.

I think we can probably close this and just track via #169.
