### ISSUE TITLE
Language code resolution endpoint

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#274]
Endpoint: **translation/languages**

Input:
* engineType: string
* languageCode: string
* engineModel (optional): string (future)

Output:
* resolvedLanguageCode: string
* nativeSupportInModel: T/F

**Comment by johnml1135** [comment]
@Nateowami, @pmachapman (CC @ddaspit ) - what exactly do you want to use this for?  Is there any other information that you would want to use?
* If you want to only use it after an engine is created, we could just give the resolved or supported field in corpora or engine fields
* Are you wanting which scripts are supported in a language?
* Is there any other information that you would want?

**Comment by Nateowami** [comment]
@johnml1135 I can't give an exhaustive list of everything we might want it for (Peter would be better at coming up with use cases), but we absolutely need it before an engine is created so we can tell the user whether their project is supported.

And Peter saw some utility in specifying which language code it maps to, rather than just whether it's a supported language.

**Comment by pmachapman** [comment]
The primary use case I can think of is to verify that a language is supported by Serval before creating the engine. `resolvedLanguageCode` would be helpful to see what it maps to.

**Comment by johnml1135** [comment]
https://github.com/sillsdev/serval/pull/283
