### ISSUE TITLE
No training data, not (both languages in NLLB) - unprocessable content 

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#284]
Spin off from https://github.com/sillsdev/serval/issues/255.

In machine, count the number of training lines of code.
Then check both languages if they are in the NLLB.
If at least one is not and there is no training data, fail the build, and return a "Unproccessable Content" error that Serval takes up and reports as a 422.

**Comment by johnml1135** [comment]
In `NmtPreprocessBuildJob`, check trainCount and whether the convertToFlores200 is sucessfull or not and then throw the error.  Wait until #309 is complete.

**Comment by ddaspit** [comment]
The main issue is that `NmtPreprocessBuildJob` is an asynchronous job. This issue is about returning a synchronous status code from the start build endpoint. This means that we would have to refactor the code in `NmtPreprocessBuildJob` to be run synchronously when the start build endpoint is called. I would really prefer not to do this, because preprocessing can be a heavy task, especially if the corpus is large.

**Comment by johnml1135** [comment]
Can we at least have the build fail then - not use "unprocessable content" but say as much in the failure code?

**Comment by ddaspit** [comment]
Yes, that is very much doable.

**Comment by Enkidu93** [comment]
> In `NmtPreprocessBuildJob`, check trainCount and whether the convertToFlores200 is sucessfull or not and then throw the error. Wait until #309 is complete.

This is very straightforward to add - just checking since this issue has been sitting a while, is this still the procedure we'd like? @johnml1135 @ddaspit
