### ISSUE TITLE
TextId when adding corpus is unclear

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#3]
TextId is used to match files in the source and target language.  This language is not clear - I recommend something like MatchId, AssociationId, ParaId.

**Comment by ddaspit** [comment]
`textId` is used to represent an individual text within a corpus. It is used in multiple places throughout the REST API. Here are a couple of examples:

- I just moved pretranslation configuration from corpus to build, so that it can be configured differently for each build. One of the the features, I added was the ability to specify which texts to pretranslate. The model for pretranslation configuration looks like this:

```json
{
  "pretranslate": [
    {
      "corpusId": "<corpus_id>",
      "textIds": ["<text_id>"]
    }
  ]
}
```
- You can also retrieve pretranslations by `textId` using the `{id}/corpora/{corpusId}/pretranslations/{textId}` endpoint.

A name like `matchId` or `associationId` would only make sense within the context of a corpus configuration. I think it would probably be best to stick with `textId` and clarify in documentation.

**Comment by johnml1135** [comment]
Ok - the change appears sound (A book of the bible you want to pretranslate one once will become a source on a future build) and the clarification on the documentation in swagger should be sufficient to avoid the confusion I had when implementing the sample process.  Let's leave this open until the documentation updates have been made.
