### ISSUE TITLE
Pretranslate already written text

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#370]
The SF user often is wanting to pretranslate text they have already written to compare against as a review tool.  Serval does not have a good workflow for this, especially if the user wants USFM in the target USFM structure.  Here is a possible way to do it:
* Add a flag when building under each pretranslation entry of `pretranslateExistingText` which will instruct Serval to pretranslate text even if there is already text in the target for that verse. Default to false (preserve current behavior).
* Add a flag for USFM called `textOrigin` which can be `preferExisting`, `preferPretranslated`, `onlyPretranslated` and `onlyExisting`. Default to `preferExisting` (preserve current behavior).

Also, we need to confirm that we will use the fresh Paratext zip file when generating this USFM combo file. 

This was requested by SF users (Bethany, etc.) and designed with @pmachapman.  @ddaspit, do you have any comments?

**Comment by ddaspit** [comment]
It doesn't make sense to pretranslate verses that are in the training corpus. The model will just spit out the target text in the training corpus. SF can already control what is included in the training corpus and what is pretranslated using `trainOn` and `pretranslate` when starting a build. Would that be sufficient?

**Comment by johnml1135** [comment]
These controls were requested by Peter/Bethany assuming that through SF, they would remove the desired book from training through the book/chapter filters, i.e., they want to review Luke so they would remove it from the training set.

The options for different presentations of the USFM is to enable different presentations of the data (all in the target USFM structure) to enable use cases such as:
* Blue/black text from existing/new (need both AI `onlyExisting` and `preferExisting`)
* Review already written chapters against an AI draft (need `onlyPretranslated`)

These have become particularly relevant as SF is now relying upon Serval to merge the USFM, instead of doing it internally.  They are therefore losing some functionality in the change and want to recover it.

**Comment by ddaspit** [comment]
I think I understand a bit better what is being requested.

For the `pretranslateExistingText` parameter, I think we should consider changing the current behavior, so that Serval always pretranslates verses that aren't in the training corpus even if there is already text in the target. This would make the `pretranslateExistingText` option unnecessary. I don't know if anyone would want the current behavior. If changing the behavior would break SF, then we should add the parameter and preserve the current behavior.

I can understand the purpose of the `textOrigin` parameter.
