### ISSUE TITLE
Exception thrown when no training data is selected

### ISSUE THREAD

**Issue by Nateowami** [sillsdev/serval#386]
Source was Spanish, and target was English, so no training data should be required in order to generate a draft. However, the build failed with this:

> Message: The build configuration was invalid. Status: 400 Response: "The scripture range is not valid: Invalid syntax. If you are providing multiple selections, e.g. a range of books followed by a selection of chapters from a book, separate each selection with a semicolon."
Translation Engine Id: 66356177d874d81aa4ebaa0e

**Comment by Nateowami** [comment]
This seems to be almost the opposite of #383. I don't understand how both are possible.

**Comment by pmachapman** [comment]
A sample build POST that caused this error on Serval QA:
`POST /translation/engines/663935afd3673074e65b4cbb/builds`
```JSON
{
  "trainOn": [
    {
      "corpusId": "663935b2d3673074e65b4cbe",
      "scriptureRange": ""
    }
  ],
  "pretranslate": [
    {
      "corpusId": "663935b2d3673074e65b4cbe",
      "scriptureRange": "PS2"
    }
  ],
  "options": {
    "max_steps": 20
  }
}
```

@Nateowami Both are possible because of our change to Scripture Forge to specify Scripture Rage as a string, not an array of books. #383 was created before this change, i.e. it specifies the `textIds` array instead of `scriptureRange`.
