### ISSUE TITLE
100% CPU for week

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#484]
What caused it?

Lots of DB queries.  Could be locks or hangfire monitoring or something else.
![Screenshot 2024-09-10 9 35 04 AM](https://github.com/user-attachments/assets/bfd665cc-afc1-4e70-9177-f3df55120fdd)
![image (1)](https://github.com/user-attachments/assets/410cf62c-8c95-4e3d-b375-e0345b85a4de)

**Comment by johnml1135** [comment]
Prod_machine.locks: 95/min
prod_machine_jobs.hangfire.lock: 40/min
prod_serval_jobs.hangfire.lock: 40/min

**Comment by johnml1135** [comment]
So there is a spare lock that has been there for over a day, but not on the engine of interest.  There was a 499 operation canceled (Timeout?) for GetWordGraph right before it all started.

After restarting the engines, it all went back to normal.

The locks are the ones that are doing something weird - 600 commands per second on the production locks...

What is happening?

**Comment by ddaspit** [comment]
From my investigation, it looks like there are a lot of commands being run, but I can't determine what the commands are. The translation engine whose call was canceled doesn't seem to exist in the database. I can't find any way that the current lock implementation would fire off so many commands. The recent (PR #486) that I fixed in the lock could have something to do with this. Without any more information, I am out of ideas.

**Comment by ddaspit** [comment]
I submitted a PR (#491) that might reduce the chances of this happening.

**Comment by johnml1135** [comment]
Let's say this is resolved unless it comes back.
