### ISSUE TITLE
The autoscalar job didn't complete - why?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#568]
It seemed to complete, but then hung for an hour.  It did it a few times.  What gives?

https://app.sil.hosted.allegro.ai/projects/*/experiments/70ab3ccf279f417b9ef7f275da3b969f/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&deep=true

![Image](https://github.com/user-attachments/assets/84bdbc47-cf3a-49d2-b388-97485083967c)

**Comment by mshannon-sil** [comment]
The strange thing is that even though the task is stuck in the `Running` state, the message in the Info section says `Completed`. I've reached out to ClearML support to see if they have an idea of what is happening.

**Comment by johnml1135** [comment]
There needs to be one more line `Process completed successfully`.  That is not in the file but in ones that have actually completed.  The only thing that runs after logging "Finished" is that the `scheduler` stops.  Either that could be at issue or something else.

**Comment by mshannon-sil** [comment]
Figured out what's happening with the autoscaler with ClearML support. The max idle time was set to 1 min for the autoscaler, which is pretty low, and since it took slightly longer than a minute for the next E2E test to start, the autoscaler sent a command to GCP to delete the instance right before the task started, and the deletion process takes about 30 seconds to complete. I can fix this by increasing the max idle time from 1 min to 5 min so we don't run into these kinds of edge cases.

**Comment by mshannon-sil** [comment]
Just relaunched the autoscaler instances with the updated max idle time.

**Comment by johnml1135** [comment]
Rerunning https://github.com/sillsdev/serval/actions/runs/12280974996 - if it passes, we can close out the issue.

**Comment by johnml1135** [comment]
It passed.  Closing.
