### ISSUE TITLE
Make Echo engine truly "echo" NMT engines

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#66]
For full testing for NMT backtranslation drafting by SF.  Talk to Peter for details on what is wrong.

**Comment by pmachapman** [comment]
Here is [sample data](https://github.com/sillsdev/serval/files/12178544/Sample.Data.zip) you can use to create a test for the Echo engine.

To use it (I did this via Swagger):
```
POST /translation/engines
{
  "name": "Echo Test",
  "sourceLanguage": "grc",
  "targetLanguage": "en",
  "type": "Echo"
}

... POST all 4 files, recording IDs ...

POST /translation/engines/64c1c3e99c64725d27b63abc/corpora
{
  "name": "pretranslation",
  "sourceLanguage": "grc",
  "targetLanguage": "en",
  "sourceFiles": [
    {
      "fileId": "64c1c5219c64725d27b63abd",
      "textId": "40_1"
    },
    {
      "fileId": "64c1c5f79c64725d27b63abf",
      "textId": "65_1"
    }
  ],
  "targetFiles": [
    {
      "fileId": "64c1c57e9c64725d27b63abe",
      "textId": "40_1"
    },
    {
      "fileId": "64c1c60e9c64725d27b63ac0",
      "textId": "65_1"
    }
  ]
}

POST /translation/engines/64c1c3e99c64725d27b63abc/builds
{
  "pretranslate": [
    {
      "corpusId": "64c1c83d9c64725d27b63ac1",
      "textIds": [
        "40_1",
        "65_1"
      ]
    }
  ]
}
```
I had this fail at the build stage for me (not sure why - the error was "Could not find a part of the path '/var/lib/serval/files/s01vt5e0.stg'."), but when the build is successful, it should return pre-translation suggestions that use the translation from the source text with the ref matching the refs in the target test (e.g. verse_001_002), i.e.
```
[
  {
    "textId": "40_1",
    "refs": [
      "40_1:verse_001_001"
    ],
    "translation": "Βίβλος γενέσεως Ἰησοῦ Χριστοῦ , υἱοῦ Δαβίδ , υἱοῦ Ἀβραάμ ."
  },
  {
    "textId": "40_1",
    "refs": [
      "40_1:verse_001_002"
    ],
    "translation": "Ἀβραὰμ ἐγέννησε τὸν Ἰσαάκ · Ἰσαὰκ δὲ ἐγέννησε τὸν Ἰακώβ · Ἰακὼβ δὲ ἐγέννησε τὸν Ἰούδαν καὶ τοὺς ἀδελφοὺς αὐτοῦ ·"
  },
  ...
]
```

**Comment by Enkidu93** [comment]
I am actively looking into it. I just returned from a trip; I apologize for not getting to this sooner. It looks like there is an attempt at covering the endpoint, but it's difficult to debug. I'll be working some tomorrow as well, and hopefully, I can get a fix soon. Thank you for the sample data!

**Comment by Enkidu93** [comment]
@pmachapman @johnml1135 Sorry for the delay! The issue ended up being that the echo engine couldn't handle the tab-delimited, custom ref format for text files. I've fixed that. I'm seeing results now that look like yours except that, as per my understanding of the documentation, a pretranslation with in-line defined references would be more like 
`...
"refs": [
      "verse_001_002"
    ],
...`
Once the outstanding PRs are merged, you should be set to go. Let me know if you have any other issues.

**Comment by pmachapman** [comment]
@Enkidu93 No worries about any delay.

Are we able to get the refs matching the refs returned by NMT (i.e. with the "{booknumber}_{chapter}:" prefix)? (see the screenshot from serval below)

![image](https://github.com/sillsdev/serval/assets/8665431/7bb139b9-f927-409a-a4da-9978224678b2)

**Comment by Enkidu93** [comment]
You mean include a prefix like "{textId}_:" even with the user-specified refs?

**Comment by pmachapman** [comment]
> Yes - prefixing the ref with "{textId}:", so it can mimic the output from Nmt in the screenshot.

**Comment by Enkidu93** [comment]
> > @pmachapman You mean include a prefix like "{textId}_:" even with the user-specified refs?
> 
> @Enkidu93 Yes - prefixing the ref with "{textId}:", so it can mimic the output from Nmt in the screenshot.

Alrighty, should be as you like it now.

**Comment by pmachapman** [comment]
Thanks @Enkidu93 - I am just testing it out now locally and comparing to Nmt's output.

Only a couple of minor changes:

1. I notice that if the first line of the target file is blank but has a sentence start (ss), in range (ir), or range start (rr) in the last column, then the pre-translation is not populated for that line when it should be (see the sample file target_40_1.txt). This is because of the following line:
```cs
l => l.Split('\t').LastOrDefault("").Trim()
```
which should be:
```cs
l => l.Split('\t')[1].Trim()
```
or maybe if you want range checking:
```cs
l => l.Contains('\t') ? l.Split('\t')[1].Trim() : string.Empty
```

(if a third column is preset - i.e. there are two tabs - the last column is codes for sentence start, range start, etc; which echo does not need to do anything with)

2. I also notice that pre-translations are not generated for target chapters with content (NMT returns pre-translations for all target segments).

Perhaps the easiest way to solve these two issues, is to change the following code which appears twice in `TranslationEngineServiceV1.cs` from:
```cs
if (sourceLine.Length > 0 && targetLine.Length == 0)
```
to:
```cs
if (sourceLine.Length > 0)
```
If Echo could return the targetLine if the targetLine is not empty, that would be really helpful. (I believe that is what NMT does?). Apologies for not making this requirement in my initial request.

Thank you so much for your work - this will make things a lot easier for us when working on pre-translations in Scripture Forge!

**Comment by Enkidu93** [comment]
@pmachapman 
1. Oh, I apologize. I wasn't thinking about the column codes causing issues. Thank you for catching that. That's a simple fix.
2. I'm not sure I understand this one. "Pretranslations are not generated for target chapters with content"? That check only governs a single line. I can certainly change it so pretranslations are generated regardless of whether there's a matching target line, but I just wanted to verify given you said "chapter". I'm new to these workflows, so I'm sure I'm doing something silly (and apparently already have haha). 
(3. I can certainly make the Echo engine just return the targetLine if that's helpful. That wasn't my impression from the controller function headers, but that probably just means I need to make them clearer :) ).  

Thank you for doing the digging yourself; that's very kind. I might not get to these tonight, but I certainly will in the morning!

Eli

**Comment by pmachapman** [comment]
> I'm not sure I understand this one. "[P]retranslations are not generated for target chapters with content"? That check only governs a single line. I can certainly change it so pretranslations are generated regardless of whether there's a matching target line, but I just wanted to verify given you said "chapter". I'm new to these workflows, so I'm sure I'm doing something silly (and apparently already have haha).

No worries - you are doing everything right. Apologies - by chapters I wasn't very clear - I meant files (we upload a file per chapter, so the two are analogous in my mind). I should have said that pre-translations should be generated for each line regardless of whether there is a matching target line - returning the target line in cases where it is not blank would be perfect.

**Comment by Enkidu93** [comment]
@pmachapman 

One last question (just so that you get the behavior you expect): For situations where you're using the in-line, user-defined references (e.g. "verse_001_001"), you expect output as follows in the given contexts:

|  | Target contains reference and matching content | Target contains reference but no content | Target does not contain reference |
|--------|--------|--------|--------|
| **Source contains reference** | Target content | Source content | Source content or SKIP? |
| **Source does not contain reference** | Target content? | SKIP? | SKIP |

Let me know. Sorry for all the back and forth. Hopefully, this will settle it and make it perfectly clear :).

**Comment by pmachapman** [comment]
@Enkidu93 What you describe is very close:

  | Target contains reference and matching content | Target contains reference but no content | Target does not contain reference
-- | -- | -- | --
**Source contains reference** | Target content | Source content | SKIP
**Source does not contain reference** | Target content | Target content (i.e. blank) | SKIP

No problem RE: back and forth - it is easier to figure out here than after deployment!

Thank you!

**Comment by Enkidu93** [comment]
I believe everything is as we've discussed. Let me know if anything else pops up. Thank you for your graciousness & time.

**Comment by Enkidu93** [comment]
For tab-delimited files with user-defined line references, the Echo engine has the following behavior:

|  | Target contains reference and matching content | Target contains reference but no content | Target does not contain reference |
|--------|--------|--------|--------|
| **Source contains reference** | Target content | Source content | SKIP |
| **Source does not contain reference** | Target content | Target content (i.e. empty string) | SKIP |

For files that are not tab-delimited, auto-generated refs are used (i.e. {textId}:{lineNum}) and the Echo engine outputs a translation for every non-empty line in the source. For a given line, if the target line is non-empty, the translation is the target line; otherwise, the translation is the source line.

For textIds that have no target file, the Echo engine outputs the source text for each line that has text.

**Comment by pmachapman** [comment]
Thanks @Enkidu93 - I have just tested Echo locally now, and it works brilliantly. Thank you so much!

**Comment by ddaspit** [comment]
I had always intended to use the Machine library the behavior of the Machine engines. I was waiting to ship a 3.0 release of the Machine library, which I would then use in the Echo engine. This would give us the exact same behavior for the Echo and Machine engines.

**Comment by Enkidu93** [comment]
> I had always intended to use the Machine library the behavior of the Machine engines. I was waiting to ship a 3.0 release of the Machine library, which I would then use in the Echo engine. This would give us the exact same behavior for the Echo and Machine engines.

@johnml1135 and I wondered about that. That would be very helpful.
