### ISSUE TITLE
Pass through configuration error reporting from ClearML

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#67]
We should pass through an error string/exception trace, etc. to Serval and it's clients when a build job fails.  We can do this by:
* Machine.py writes a file called error.log to the S3 bucket
* Machine (dotnet) reads the file if there is an error and forwards it onto Serval
* Serval adds it to the Mongo DB in the Build for "message/failure reason/etc."

**Comment by johnml1135** [comment]
May also be able to parse the ClearML console output if there is no error.log created and there is a failure - may be able to catch "out of memory" and other catastrophic failures.

**Comment by johnml1135** [comment]
Let's scope this - when there is a configuration error that Machine is not able to meaningfully assess (YAML configuration, if previous builds exist to start from, etc.) then Machine.py should pass an error log back to machine with a short, understandable message that users can take action on (fix your JSON, that build does not exist or does not have a saved model, etc.).  What is the best way to do this?

**Comment by johnml1135** [comment]
If there is an error later on, an actual bug in the software, not the config, just say "server error" or similar.

**Comment by johnml1135** [comment]
This may be best accomplished through:
* Using the ClearML Logger - and sending up an error message
* Machine-job (.net) grabs the data from the log and finds the last error
* If there is one, it takes the error message and reports it to Serval

**Comment by johnml1135** [comment]
I found something - clearMLTask.StatusReason.  Can we use this?  If we fail the job, we should be able to post a "status reason" that is a few lines.  Can we?

**Comment by mshannon-sil** [comment]
I agree with using `mark_failed()` to set the `status_reason`, I was just looking at that yesterday evening. I talked with Eli this morning, and he says that Machine.NET can then take the `status_reason` and pass it along.

@johnml1135 Eli and I were wondering whether it might make more sense to work on [Configure builds for saving models, inference only and custom starting points](https://github.com/sillsdev/serval/issues/45) before implementing this issue, since we need to have configurations in place before we can test the config error reporting. What do you think?

**Comment by ddaspit** [comment]
I think we can add it now. If a ClearML task fails for any reason, we don't pass the reason back to the engine server. Config errors are just one type of reason that a task might fail.

**Comment by Enkidu93** [comment]
OK. When John and I talked about this last in person, we were thinking that maybe a lot of errors should not be passed back up (at least not all the way to the user - maybe we would want some logged for alerting or debugging purposes) since many errors that would be classified under 500 codes are not errors that a user can fix. The error message that might otherwise be useful for debugging the issue for us wouldn't be of much use to users except to confuse them and remove the sense of abstraction. But configuration errors (once a build is configurable by users) are something a user can remedy. But maybe it's best just to pass everything up 🤷 since many of our end users will not be accessing Serval directly (is that true??).
