### ISSUE TITLE
Race condition when starting a build job can cause inconsistent behavior

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#95]
The `TranslationEnginesController` checks if a current job is active prior to starting a build job. If a build job is active, the endpoint returns a 409. If a build job becomes active after the check but before the build job is actually started, then the currently active build job will be canceled and a new job started. This happens because of different behavior between the Machine engines and Serval when starting a job. The Machine engines will cancel a job if there is an active job before starting a new job. We should either remove the check in Serval or change the behavior of Machine to fail if there is an active job.

**Comment by johnml1135** [comment]
What is the desired behavior? If a person wants to override an existing build with a new build, it makes sense to first issue, a cancel and then a request to build.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Damien Daspit ***@***.***>
Sent: Friday, August 18, 2023 5:30:32 PM
To: sillsdev/serval ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sillsdev/serval] Race condition when starting a build job can cause inconsistent behavior (Issue #95)


The TranslationEnginesController checks if a current job is active prior to starting a build job. If a build job is active, the endpoint returns a 409. If a build job becomes active after the check but before the build job is actually started, then the currently active build job will be canceled and a new job started. This happens because of different behavior between the Machine engines and Serval when starting a job. The Machine engines will cancel a job if there is an active job before starting a new job. We should either remove the check in Serval or change the behavior of Machine to fail if there is an active job.

**Comment by ddaspit** [comment]
That is a good question. I'm not sure which is better. Requiring a build to be canceled first is more explicit, but potentially more error-prone because of timing issues. This can result in race conditions where the API will return error status codes if the engine is in the wrong state. The calling application will need to be able to handle these error codes gracefully.

**Comment by ddaspit** [comment]
Sounds fine to me. We need to update Machine so that it doesn't cancel the current build when a new one is started.

**Comment by johnml1135** [comment]
@Enkidu93 - can you fix it so that according to the first comment, 2 build requests are made one after the other and it gets past the first 409 checking but then when it tries to start the next build, instead of cancelling the existing one, it yield a 409 or some other thing.

Here is the code that cancels the existing job that would need to change:
https://github.com/sillsdev/machine/blob/80fbaf067b3bdb27475d96d841de3df22ff68b7e/src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs#L122-L137

**Comment by Enkidu93** [comment]
OK, can do! Would you like this added to a certain milestone? (Just wondering how to prioritize).

**Comment by johnml1135** [comment]
If it's easy enough to do now, let's just push it out.  I don't know how hard it would be to float the error back up.

**Comment by Enkidu93** [comment]
See: https://github.com/sillsdev/machine/pull/72
